/* Generated by Strata. */
_Static_assert(sizeof(int) == 4, "Strata requires 32-bit int");
extern void* strata_alloc(unsigned long);
extern void strata_free(void*);
static char* strata_strdup(const char* s) {
  unsigned long n = 0; while (s[n]) n++;
  char* d = (char*)strata_alloc(n + 1);
  if (d) { unsigned long i; for (i = 0; i <= n; i++) d[i] = s[i]; }
  return d;
}
extern float fmodf(float, float);
extern double fmod(double, double);

#include <immintrin.h>


#line 3 "../samples/simd.strata"
int run(int strata__var_seed);

#line 3 "../samples/simd.strata"
int run(int strata__var_seed) {
    __m128 strata__var_a = _mm_setr_ps(1.000000000e+00f,2.000000000e+00f,3.000000000e+00f, 0.0000f);
    __m128 strata__var_b = _mm_setr_ps(4.000000000e+00f,5.000000000e+00f,6.000000000e+00f, 0.0000f);
    __m128 strata__var_z = _mm_permute_ps(strata__var_a,_MM_SHUFFLE(3,0,0,0));
    __m128 strata__var_result = _mm_add_ps(strata__var_a,strata__var_b);
    return (int){0};
}

