/* Generated by Strata. */
_Static_assert(sizeof(int) == 4, "Strata requires 32-bit int");
extern void* strata_alloc(unsigned long);
extern void strata_free(void*);
static char* strata_strdup(const char* s) {
  unsigned long n = 0; while (s[n]) n++;
  char* d = (char*)strata_alloc(n + 1);
  if (d) { unsigned long i; for (i = 0; i <= n; i++) d[i] = s[i]; }
  return d;
}
extern float fmodf(float, float);
extern double fmod(double, double);

#include <arm_neon.h>


#line 2 "../samples/simd.strata"
float32x4_t test1(float32x4_t strata__var_x, float32x4_t strata__var_y);
#line 8 "../samples/simd.strata"
int run(int strata__var_seed);

#line 2 "../samples/simd.strata"
float32x4_t test1(float32x4_t strata__var_x, float32x4_t strata__var_y) {
    return strata__var_y;
    }

#line 8 "../samples/simd.strata"
int run(int strata__var_seed) {
    float32x4_t strata__var_result = test1((float32x4_t) {1.000000000e+00f,2.000000000e+00f,3.000000000e+00f, 0.0000f}, (float32x4_t) {4.000000000e+00f,5.000000000e+00f,6.000000000e+00f, 0.0000f});
    return (int){0};
}

