if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "GenerateTccPredefs.cmake requires INPUT and OUTPUT")
endif()

file(READ "${INPUT}" content)
string(REPLACE "\\" "\\\\" content "${content}")
string(REPLACE "\"" "\\\"" content "${content}")
string(REPLACE "\r\n" "\n" content "${content}")
string(REPLACE "\r" "\n" content "${content}")
string(REPLACE "\n" "\\n\"\n\"" content "${content}")
get_filename_component(output_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
file(WRITE "${OUTPUT}" "\"${content}\"\n")
